GET http://localhost:3000/

###

POST http://localhost:3000/register
Content-Type : application/json

{
    "username":"ami",
    "password":"1234",
    "email":"ammar@gmail.com",
    "name":"ammar"
}
###
POST http://localhost:3000/login
Content-Type : application/json

{
    "username": "ami",
     "password":"1234"
}